//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.24 at 11:19:51 ���� CST 
//


package com.zhiwei.credit.service.thirdPay.fuiou.model.req.qrytrans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zhiwei.credit.service.thirdPay.fuiou.model.req.qrytrans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Qrytransreq_QNAME = new QName("", "qrytransreq");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zhiwei.credit.service.thirdPay.fuiou.model.req.qrytrans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QryTransReqType }
     * 
     */
    public QryTransReqType createQryTransReqType() {
        return new QryTransReqType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QryTransReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "qrytransreq")
    public JAXBElement<QryTransReqType> createQrytransreq(QryTransReqType value) {
        return new JAXBElement<QryTransReqType>(_Qrytransreq_QNAME, QryTransReqType.class, null, value);
    }

}
